### PR TITLE
Remove deprecated functions

### PR DESCRIPTION
**Pull request by ngochc**
Remove deprecated functions including:
- newTaskReport
- newConfigDiff
- RetryExecutor
- Timestamp

### CODE REVIEW

**Review by vietnguyen-td — APPROVED** [review]
LGTM

**Review by dmikurube — APPROVED** [review]
Thanks for working on it! LGTM.

**Review by nmpennypacker — APPROVED** [review]
Reviewed for data exfiltrations

**Comment by dmikurube** [comment]
Let me merge this, and release 0.4.1. Thanks!

**Pull request merged**
