### PR TITLE
Concurrent fetching base target and related objects

### PR DESCRIPTION
**Pull request by tvhung83**
I added `thread` as dependency. The reason is, if I use `Queue` (native Ruby multithreading model), I will have to push all records into it, and pop one by one in in a loop to produce threads, which concerns me about memory consumption.
Besides, I noticed a performance boost by using `thread` gem, compared to native thread, the code looks cleaner too.

### CODE REVIEW

**Review by muga — APPROVED** [review]
It sounds good for me. @uu59 can you take a look?

**Review by uu59 — APPROVED** [review]
Looks good 👍

**Comment by tvhung83** [comment]
Thanks @uu59 for looking into it, will resolve conflicts now.

**Comment by uu59** [comment]
CI failed due to this commit make the version fixed: https://github.com/treasure-data/embulk-input-zendesk/commit/bc94c033b5cf61ac31b12ae1b3581d168d6361d0
But this PR expects codeclimate-test-reporter 1.x or higher.

**Pull request merged**
