### PR TITLE
Fix mem leak by yielding each record in `export_parallel()` method

### PR DESCRIPTION
**Pull request by tvhung83**
- Remove unnecessary mutex
- Avoid storing all records in memory

### CODE REVIEW

**Comment by tvhung83** [comment]
hi @sakama -san, please help take a look when you can 🙂

**Comment by ylzen** [comment]
@tvhung83 Is there a Jira ticket for this PR?

**Review by sakama — APPROVED** [review]
LGTM

**Comment by tvhung83** [comment]
Thank you, @sakama -san, will merge now 🙂

**Pull request merged**
