### PR TITLE
Add 3 properties to include app marketplace API headers

### PR DESCRIPTION
**Pull request by vinhvd**
Follow up https://help.zendesk.com/hc/en-us/articles/115010249348-Announcing-Updated-Apps-Marketplace-API-Header-Requirements.

All partners that wish to be a part of the Zendesk Apps Marketplace will be required to include the following custom headers for any requests to the Zendesk API from an external source:

X-Zendesk-Marketplace-Name:"App Name for Zendesk"
X-Zendesk-Marketplace-Organization-Id:12345
X-Zendesk-Marketplace-App-Id: 99999

### CODE REVIEW

**Review by sakama — COMMENTED** [review]
Basically, looks good to me.
`raise Embulk::ConfigError.new` is better when all of `app_marketplace_integration_name` , `app_marketplace_org_id`, `app_marketplace_app_id` aren't filled out.

**Comment by vinhvd** [comment]
Thanks @sakama for your review/feedback, 3 new properties are optional, do we still need to raise ConfigError ?

**Comment by sakama** [comment]
@vinhvd I think so because some user might not think 3/3 value are needed to enable this request.
What I meant is...
0/3 value is set > Don't raise
1/3, 2/3 value are set > Raise

**Comment by vinhvd** [comment]
@sakama Thanks for detail explanation. Yes, it's great to have.

**Comment by vinhvd** [comment]
@sakama when you get time, please review again. Thanks.

**Review by sakama — APPROVED** [review]
LGTM

**Pull request merged**
