### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by NirmalaY12**
Code scanning is a feature that you use to analyze the code in a GitHub repository to find security vulnerabilities and coding errors.

### CODE REVIEW

**Comment by DrShaneGreen** [comment]
Need to have this PR reviewed and merged. No impact to deployments

**Comment by DrShaneGreen** [comment]
Following up on this PR to get merged. Can someone review and merge this PR for code scanning ?

**Comment by DrShaneGreen** [comment]
@nahi and @treasure-data/integrations-admin 
I pushed an empty commit to ensure that the CodeQL will run successfully.

No issues were found.

Can we get this PR merged to master.
Thanks

**Review by kietdo360 — APPROVED** [review]
LGTM

**Pull request merged**
